### PR TITLE
Add some more documentation to the README

### PR DESCRIPTION
**Pull request by rreusser**
I had to sift through a few pages of https://www.npmjs.com/search?q=unique before finding a module that  didn't simply sort and then filter out adjacent duplicates, and then I had to try a few out to be sure.

No changes to the code. I've added some documentation that makes the implications of the `Set` approach more clear.

### CODE REVIEW

**Comment by rreusser** [comment]
Oops. Before merging, I guess the thing to do is to double-check that `Set` actually guarantees this behavior!

**Comment by rreusser** [comment]
The standard is a little tricky to follow:

http://www.ecma-international.org/ecma-262/6.0/#sec-set-objects

But the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) are a bit more straightforward:

> Set objects are collections of values, you can iterate its elements in insertion order.

**Comment by vikramcse** [comment]
Thank You @rreusser for the contribution, I just recently started OSS stuff. From next time I will look forward to clean and detailed documentation.

**Comment by rreusser** [comment]
Cool, thanks! And no worries! I just like to add a couple words and details here and there as I use stuff. Your module worked great for us. It will be in the app store shortly. :smile:

**Pull request merged**
